"""Regression tests comparing Python output to R reference output.

This test suite validates that the Python implementation produces results
similar to the original R implementation by comparing against reference
.feather files generated by the R version.
"""

from pathlib import Path

import pandas as pd
import pytest

from hypoparsr import parse_file
from hypoparsr.utils.similarity import (
    calculate_overall_similarity,
    compare_dataframes,
)


class TestRCompatibility:
    """Test suite for R compatibility regression tests."""

    @pytest.fixture
    def data_dir(self) -> Path:
        """Get path to test data directory."""
        return Path(__file__).parent.parent / "data"

    @pytest.fixture
    def original_dir(self, data_dir: Path) -> Path:
        """Get path to original CSV files."""
        return data_dir / "original"

    @pytest.fixture
    def reference_dir(self, data_dir: Path) -> Path:
        """Get path to R reference outputs."""
        return data_dir / "cleaned"

    @pytest.fixture
    def csv_reference_pairs(
        self, original_dir: Path, reference_dir: Path
    ) -> list[tuple[Path, Path]]:
        """Get list of (CSV file, reference .feather) pairs."""
        pairs = []

        # Find all CSV files that have reference outputs
        for csv_file in original_dir.glob("*.csv"):
            reference_file = reference_dir / f"{csv_file.name}.feather"
            if reference_file.exists():
                pairs.append((csv_file, reference_file))

        return pairs

    @pytest.fixture
    def sample_pairs(
        self, csv_reference_pairs: list[tuple[Path, Path]]
    ) -> list[tuple[Path, Path]]:
        """Get sample of pairs for faster testing."""
        # Return first 10 for faster testing
        return csv_reference_pairs[:10]

    def test_reference_files_exist(
        self, csv_reference_pairs: list[tuple[Path, Path]]
    ) -> None:
        """Test that reference files exist."""
        assert len(csv_reference_pairs) > 0, "No reference files found"
        print(f"\nFound {len(csv_reference_pairs)} CSV/reference pairs")

    def test_sample_compatibility(
        self, sample_pairs: list[tuple[Path, Path]]
    ) -> None:
        """Test compatibility on sample of files."""
        results = []

        for csv_file, reference_file in sample_pairs:
            try:
                # Parse with Python
                python_result = parse_file(str(csv_file), preset="lenient")
                python_df = python_result.to_dataframe()

                # Load R reference
                r_df = pd.read_feather(reference_file)

                # Calculate similarity
                similarity = calculate_overall_similarity(python_df, r_df)

                results.append(
                    {
                        "file": csv_file.name,
                        "similarity": similarity,
                        "python_shape": python_df.shape,
                        "r_shape": r_df.shape,
                    }
                )

                # Log result
                print(f"\n{csv_file.name}:")
                print(f"  Similarity: {similarity:.3f}")
                print(f"  Python: {python_df.shape}, R: {r_df.shape}")

            except Exception as e:
                print(f"\nError processing {csv_file.name}: {e}")
                results.append(
                    {
                        "file": csv_file.name,
                        "similarity": 0.0,
                        "error": str(e),
                    }
                )

        # Summary statistics
        similarities = [r["similarity"] for r in results if "error" not in r]
        if similarities:
            avg_similarity = sum(similarities) / len(similarities)
            min_similarity = min(similarities)
            max_similarity = max(similarities)

            print(f"\n\nSummary:")
            print(f"  Files tested: {len(results)}")
            print(f"  Average similarity: {avg_similarity:.3f}")
            print(f"  Min similarity: {min_similarity:.3f}")
            print(f"  Max similarity: {max_similarity:.3f}")

            # We expect at least some similarity on average
            assert avg_similarity > 0.3, f"Average similarity too low: {avg_similarity}"

    def test_detailed_comparison_single_file(
        self, sample_pairs: list[tuple[Path, Path]]
    ) -> None:
        """Test detailed comparison on a single file."""
        if not sample_pairs:
            pytest.skip("No sample pairs available")

        csv_file, reference_file = sample_pairs[0]

        # Parse with Python
        python_result = parse_file(str(csv_file))
        python_df = python_result.to_dataframe()

        # Load R reference
        r_df = pd.read_feather(reference_file)

        # Detailed comparison
        report = compare_dataframes(python_df, r_df, "Python", "R")

        print(f"\n\nDetailed comparison for {csv_file.name}:")
        print(f"Overall similarity: {report['overall_similarity']:.3f}")
        print("\nStructure metrics:")
        for key, value in report["structure"].items():
            print(f"  {key}: {value:.3f}")
        print("\nContent metrics:")
        for key, value in report["content"].items():
            print(f"  {key}: {value:.3f}")
        print("\nDifferences:")
        for key, value in report["differences"].items():
            print(f"  {key}: {value}")

        # Basic assertions
        assert report["overall_similarity"] >= 0.0
        assert report["overall_similarity"] <= 1.0

    @pytest.mark.parametrize("similarity_threshold", [0.5, 0.6, 0.7, 0.8, 0.9])
    def test_similarity_thresholds(
        self, sample_pairs: list[tuple[Path, Path]], similarity_threshold: float
    ) -> None:
        """Test what percentage of files meet various similarity thresholds."""
        if not sample_pairs:
            pytest.skip("No sample pairs available")

        meeting_threshold = 0
        total = 0

        for csv_file, reference_file in sample_pairs:
            try:
                python_result = parse_file(str(csv_file), preset="lenient")
                python_df = python_result.to_dataframe()

                r_df = pd.read_feather(reference_file)

                similarity = calculate_overall_similarity(python_df, r_df)

                total += 1
                if similarity >= similarity_threshold:
                    meeting_threshold += 1

            except Exception:
                total += 1

        if total > 0:
            percentage = (meeting_threshold / total) * 100
            print(
                f"\n{percentage:.1f}% of files meet {similarity_threshold:.1f} threshold "
                f"({meeting_threshold}/{total})"
            )

    def test_shape_preservation(
        self, sample_pairs: list[tuple[Path, Path]]
    ) -> None:
        """Test how well shapes are preserved."""
        exact_matches = 0
        row_matches = 0
        col_matches = 0
        total = 0

        for csv_file, reference_file in sample_pairs:
            try:
                python_result = parse_file(str(csv_file))
                python_df = python_result.to_dataframe()

                r_df = pd.read_feather(reference_file)

                total += 1

                if python_df.shape == r_df.shape:
                    exact_matches += 1
                if python_df.shape[0] == r_df.shape[0]:
                    row_matches += 1
                if python_df.shape[1] == r_df.shape[1]:
                    col_matches += 1

            except Exception:
                total += 1

        if total > 0:
            print(f"\n\nShape preservation:")
            print(
                f"  Exact shape match: {exact_matches}/{total} "
                f"({100*exact_matches/total:.1f}%)"
            )
            print(
                f"  Row count match: {row_matches}/{total} "
                f"({100*row_matches/total:.1f}%)"
            )
            print(
                f"  Column count match: {col_matches}/{total} "
                f"({100*col_matches/total:.1f}%)"
            )


class TestSimilarityMetrics:
    """Test suite for similarity calculation functions."""

    def test_identical_dataframes(self) -> None:
        """Test that identical DataFrames have similarity of 1.0."""
        df = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})

        similarity = calculate_overall_similarity(df, df)
        assert similarity == 1.0

    def test_completely_different_dataframes(self) -> None:
        """Test that very different DataFrames have low similarity."""
        df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
        df2 = pd.DataFrame({"x": ["foo", "bar"], "y": ["baz", "qux"], "z": [1, 2]})

        similarity = calculate_overall_similarity(df1, df2)
        assert similarity < 0.5

    def test_shape_mismatch_only(self) -> None:
        """Test DataFrames with same content but different shapes."""
        df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
        df2 = pd.DataFrame({"a": [1, 2], "b": [4, 5]})

        similarity = calculate_overall_similarity(df1, df2)
        # Should have moderate similarity (same content, different size)
        assert 0.5 < similarity < 1.0

    def test_content_mismatch_only(self) -> None:
        """Test DataFrames with same shape but different content."""
        df1 = pd.DataFrame({"a": [1, 2, 3], "b": [4, 5, 6]})
        df2 = pd.DataFrame({"a": [7, 8, 9], "b": [10, 11, 12]})

        report = compare_dataframes(df1, df2)

        # Shape should match perfectly
        assert report["structure"]["shape_match"] == 1.0

        # Content should not match
        assert report["content"]["cell_match_rate"] < 1.0

    def test_missing_values(self) -> None:
        """Test handling of missing values."""
        df1 = pd.DataFrame({"a": [1, None, 3], "b": [4, 5, None]})
        df2 = pd.DataFrame({"a": [1, None, 3], "b": [4, 5, None]})

        similarity = calculate_overall_similarity(df1, df2)
        assert similarity == 1.0


class TestRegressionReport:
    """Generate comprehensive regression report."""

    @pytest.fixture
    def csv_reference_pairs(self) -> list[tuple[Path, Path]]:
        """Get all CSV/reference pairs."""
        data_dir = Path(__file__).parent.parent / "data"
        original_dir = data_dir / "original"
        reference_dir = data_dir / "cleaned"

        pairs = []
        for csv_file in original_dir.glob("*.csv"):
            reference_file = reference_dir / f"{csv_file.name}.feather"
            if reference_file.exists():
                pairs.append((csv_file, reference_file))

        return pairs

    @pytest.mark.slow
    def test_generate_full_regression_report(
        self, csv_reference_pairs: list[tuple[Path, Path]]
    ) -> None:
        """Generate full regression report on all files.

        This test is marked as 'slow' and should be run with: pytest -m slow
        """
        results = []

        print(f"\n\nProcessing {len(csv_reference_pairs)} files...")

        for i, (csv_file, reference_file) in enumerate(csv_reference_pairs, 1):
            try:
                # Parse with Python
                python_result = parse_file(str(csv_file), preset="lenient")
                python_df = python_result.to_dataframe()

                # Load R reference
                r_df = pd.read_feather(reference_file)

                # Calculate detailed comparison
                report = compare_dataframes(python_df, r_df, "Python", "R")

                results.append(
                    {
                        "file": csv_file.name,
                        "overall_similarity": report["overall_similarity"],
                        "shape_match": report["structure"]["shape_match"],
                        "cell_match_rate": report["content"]["cell_match_rate"],
                        "python_shape": python_df.shape,
                        "r_shape": r_df.shape,
                        "python_confidence": python_result.best.hypothesis.confidence,
                        "warnings": len(python_result.best.warnings),
                    }
                )

                if i % 10 == 0:
                    print(f"  Processed {i}/{len(csv_reference_pairs)} files...")

            except Exception as e:
                results.append(
                    {
                        "file": csv_file.name,
                        "overall_similarity": 0.0,
                        "error": str(e),
                    }
                )

        # Create summary DataFrame
        results_df = pd.DataFrame(results)

        # Print summary statistics
        print("\n\n=== REGRESSION TEST REPORT ===")
        print(f"\nTotal files tested: {len(results)}")

        if "error" in results_df.columns:
            errors = results_df["error"].notna().sum()
            print(f"Errors encountered: {errors}")

        # Similarity statistics
        valid_results = results_df[results_df["overall_similarity"] > 0]
        if len(valid_results) > 0:
            print(f"\nSimilarity statistics (on {len(valid_results)} successful parses):")
            print(f"  Mean: {valid_results['overall_similarity'].mean():.3f}")
            print(f"  Median: {valid_results['overall_similarity'].median():.3f}")
            print(f"  Min: {valid_results['overall_similarity'].min():.3f}")
            print(f"  Max: {valid_results['overall_similarity'].max():.3f}")
            print(f"  Std: {valid_results['overall_similarity'].std():.3f}")

            # Threshold analysis
            print("\nThreshold analysis:")
            for threshold in [0.5, 0.6, 0.7, 0.8, 0.9]:
                count = (valid_results["overall_similarity"] >= threshold).sum()
                pct = 100 * count / len(valid_results)
                print(f"  >= {threshold:.1f}: {count} files ({pct:.1f}%)")

            # Shape matching
            if "shape_match" in valid_results.columns:
                shape_matches = (valid_results["shape_match"] == 1.0).sum()
                pct = 100 * shape_matches / len(valid_results)
                print(f"\nExact shape matches: {shape_matches} ({pct:.1f}%)")

        # Save detailed results
        report_file = Path(__file__).parent.parent / "regression_report.csv"
        results_df.to_csv(report_file, index=False)
        print(f"\nDetailed report saved to: {report_file}")

        # Basic assertion - at least some files should parse successfully
        assert len(valid_results) > 0, "No files parsed successfully"
